### PR TITLE
Added Avatar Component

### PR DESCRIPTION
**Pull request by Priyanshi-Tiwari**
Screenshot 2022-02-17 at 9 09 12 PM

### CODE REVIEW

**Review by Sameony — APPROVED** [review]
Nice and clean code with descriptive commit messages.
a suggestion for the layout: you can add a little margin between the avatars as they look very close and squished.

**Review by sadathshariff — APPROVED** [review]
Everything looks good use of class names

**Review by dev-enforced — APPROVED** [review]
The code looks good to me . Great work @Priyanshi-Tiwari on the avatar component and documentation.

**Comment by Priyanshi-Tiwari** [comment]
Thank you for the feedback :) @dev-enforced  @sadathshariff @Sameony !

**Pull request merged**
